### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by paul-phan**

### CODE REVIEW

**Comment by hta218** [comment]
@dangthang1903 can you help resolving conficts in this PR?

**Comment by hta218** [comment]
@paul-phan can you help to fix the build error

**Comment by hta218** [comment]
Any update on this bro @paul-phan ?

**Comment by paul-phan** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> 1 Skipped Deployment

@hta218 I updated the Vercel build script, now it will only run with the `classic-compiler` branch. Other branches will be ignored.

**Pull request merged**
